services:
  bikeservice-api:
    container_name: "bikeservice-api"
    build: .
    ports:
      - "5012:80"
    restart: unless-stopped
    extra_hosts:
    - "host.docker.internal:host-gateway"
    volumes:
      - /data/bikeservice/log:/var/log/bikeservice/
