services:
  server:
    container_name: "bikeservice-server"
    build: .
    ports:
      - '127.0.0.1:5012:80'
      - '[::1]:5012:80'
    restart: unless-stopped
    volumes:
      - /data/bikeservice/log:/var/log/bikeservice/
    environment:
      ASPNETCORE_URLS: "http://0.0.0.0:80"


