services:
  web-api:
    container_name: "bikeservice-api"
    networks:
      - bs-net
    build: .
    ports:
      - '127.0.0.1:5012:80'
      - '[::1]:5012:80'
    restart: unless-stopped
    volumes:
      - /data/bikeservice/log:/var/log/bikeservice/

networks:
  bs-net:
    external: true
