CREATE TABLE IF NOT EXISTS "__EFMigrationsHistory"
(
    "MigrationId"    character varying(150) NOT NULL,
    "ProductVersion" character varying(32)  NOT NULL,
    CONSTRAINT "PK___EFMigrationsHistory" PRIMARY KEY ("MigrationId")
);

START TRANSACTION;

CREATE TABLE "AspNetRoles"
(
    "Id"               uuid NOT NULL,
    "Name"             character varying(256),
    "NormalizedName"   character varying(256),
    "ConcurrencyStamp" text,
    CONSTRAINT "PK_AspNetRoles" PRIMARY KEY ("Id")
);

CREATE TABLE "AspNetUsers"
(
    "Id"                   uuid    NOT NULL,
    "UserName"             character varying(256),
    "NormalizedUserName"   character varying(256),
    "Email"                character varying(256),
    "NormalizedEmail"      character varying(256),
    "EmailConfirmed"       boolean NOT NULL,
    "PasswordHash"         text,
    "SecurityStamp"        text,
    "ConcurrencyStamp"     text,
    "PhoneNumber"          text,
    "PhoneNumberConfirmed" boolean NOT NULL,
    "TwoFactorEnabled"     boolean NOT NULL,
    "LockoutEnd"           timestamp with time zone,
    "LockoutEnabled"       boolean NOT NULL,
    "AccessFailedCount"    integer NOT NULL,
    CONSTRAINT "PK_AspNetUsers" PRIMARY KEY ("Id")
);

CREATE TABLE "Bikes"
(
    "Id"           uuid                     NOT NULL,
    "Manufacturer" text                     NOT NULL,
    "Model"        text                     NOT NULL,
    "Mileage"      double precision         NOT NULL,
    "Date"         timestamp with time zone NOT NULL,
    "TypeId"       uuid                     NOT NULL,
    "Status"       integer                  NOT NULL,
    "UserId"       uuid                     NOT NULL,
    CONSTRAINT "PK_Bikes" PRIMARY KEY ("Id")
);

CREATE TABLE "EquipmentTypes"
(
    "Id"       uuid    NOT NULL,
    "Name"     text    NOT NULL,
    "Category" integer NOT NULL,
    "UserId"   uuid    NOT NULL,
    CONSTRAINT "PK_EquipmentTypes" PRIMARY KEY ("Id")
);

CREATE TABLE "Parts"
(
    "Id"           uuid             NOT NULL,
    "Manufacturer" text             NOT NULL,
    "Model"        text             NOT NULL,
    "Mileage"      double precision NOT NULL,
    "Status"       integer          NOT NULL,
    "TypeId"       uuid             NOT NULL,
    "BikeId"       uuid             NOT NULL,
    "UserId"       uuid             NOT NULL,
    CONSTRAINT "PK_Parts" PRIMARY KEY ("Id")
);

CREATE TABLE "AspNetRoleClaims"
(
    "Id"         integer GENERATED BY DEFAULT AS IDENTITY,
    "RoleId"     uuid NOT NULL,
    "ClaimType"  text,
    "ClaimValue" text,
    CONSTRAINT "PK_AspNetRoleClaims" PRIMARY KEY ("Id"),
    CONSTRAINT "FK_AspNetRoleClaims_AspNetRoles_RoleId" FOREIGN KEY ("RoleId") REFERENCES "AspNetRoles" ("Id") ON DELETE CASCADE
);

CREATE TABLE "AspNetUserClaims"
(
    "Id"         integer GENERATED BY DEFAULT AS IDENTITY,
    "UserId"     uuid NOT NULL,
    "ClaimType"  text,
    "ClaimValue" text,
    CONSTRAINT "PK_AspNetUserClaims" PRIMARY KEY ("Id"),
    CONSTRAINT "FK_AspNetUserClaims_AspNetUsers_UserId" FOREIGN KEY ("UserId") REFERENCES "AspNetUsers" ("Id") ON DELETE CASCADE
);

CREATE TABLE "AspNetUserLogins"
(
    "LoginProvider"       text NOT NULL,
    "ProviderKey"         text NOT NULL,
    "ProviderDisplayName" text,
    "UserId"              uuid NOT NULL,
    CONSTRAINT "PK_AspNetUserLogins" PRIMARY KEY ("LoginProvider", "ProviderKey"),
    CONSTRAINT "FK_AspNetUserLogins_AspNetUsers_UserId" FOREIGN KEY ("UserId") REFERENCES "AspNetUsers" ("Id") ON DELETE CASCADE
);

CREATE TABLE "AspNetUserRoles"
(
    "UserId" uuid NOT NULL,
    "RoleId" uuid NOT NULL,
    CONSTRAINT "PK_AspNetUserRoles" PRIMARY KEY ("UserId", "RoleId"),
    CONSTRAINT "FK_AspNetUserRoles_AspNetRoles_RoleId" FOREIGN KEY ("RoleId") REFERENCES "AspNetRoles" ("Id") ON DELETE CASCADE,
    CONSTRAINT "FK_AspNetUserRoles_AspNetUsers_UserId" FOREIGN KEY ("UserId") REFERENCES "AspNetUsers" ("Id") ON DELETE CASCADE
);

CREATE TABLE "AspNetUserTokens"
(
    "UserId"        uuid NOT NULL,
    "LoginProvider" text NOT NULL,
    "Name"          text NOT NULL,
    "Value"         text,
    CONSTRAINT "PK_AspNetUserTokens" PRIMARY KEY ("UserId", "LoginProvider", "Name"),
    CONSTRAINT "FK_AspNetUserTokens_AspNetUsers_UserId" FOREIGN KEY ("UserId") REFERENCES "AspNetUsers" ("Id") ON DELETE CASCADE
);

CREATE TABLE "ServiceNote"
(
    "Id"      uuid                     NOT NULL,
    "Mileage" double precision         NOT NULL,
    "Date"    timestamp with time zone NOT NULL,
    "Note"    text                     NOT NULL,
    "BikeId"  uuid,
    "PartId"  uuid,
    CONSTRAINT "PK_ServiceNote" PRIMARY KEY ("Id"),
    CONSTRAINT "FK_ServiceNote_Bikes_BikeId" FOREIGN KEY ("BikeId") REFERENCES "Bikes" ("Id"),
    CONSTRAINT "FK_ServiceNote_Parts_PartId" FOREIGN KEY ("PartId") REFERENCES "Parts" ("Id")
);

CREATE INDEX "IX_AspNetRoleClaims_RoleId" ON "AspNetRoleClaims" ("RoleId");

CREATE UNIQUE INDEX "RoleNameIndex" ON "AspNetRoles" ("NormalizedName");

CREATE INDEX "IX_AspNetUserClaims_UserId" ON "AspNetUserClaims" ("UserId");

CREATE INDEX "IX_AspNetUserLogins_UserId" ON "AspNetUserLogins" ("UserId");

CREATE INDEX "IX_AspNetUserRoles_RoleId" ON "AspNetUserRoles" ("RoleId");

CREATE INDEX "EmailIndex" ON "AspNetUsers" ("NormalizedEmail");

CREATE UNIQUE INDEX "UserNameIndex" ON "AspNetUsers" ("NormalizedUserName");

CREATE INDEX "IX_ServiceNote_BikeId" ON "ServiceNote" ("BikeId");

CREATE INDEX "IX_ServiceNote_PartId" ON "ServiceNote" ("PartId");

INSERT INTO "__EFMigrationsHistory" ("MigrationId", "ProductVersion")
VALUES ('20250215193536_Init', '8.0.10');

COMMIT;