name: .NET Publish
description: Build .NET project

inputs: 
  working-directory:
    required: true
    description: "Location of .sln file"

runs: 
  using: composite
  steps:
    - name: Restore dependencies
      working-directory: ${{ inputs.working-directory }}
      shell: bash
      run: dotnet restore

    - name: Publish
      working-directory: ${{ inputs.working-directory }}
      shell: bash
      run: dotnet publish ./src/Server --no-restore -c Release -o bin