name: Docker push
description: Push docker image 

inputs: 
  working-directory:
    required: true
    description: "Location of Dockerfile"

runs: 
  using: composite
  steps:
    - name: Test
      shell: bash
      working-directory: ${{ inputs.working-directory }}
      run: echo "hello"
    - name: Help
      shell: bash
      working-directory: ${{ inputs.working-directory }}
      run: docker --help
      
    - name: Build
      shell: bash
      working-directory: ${{ inputs.working-directory }}
      run: docker build . -t testing
      
    - name: Build
      shell: bash
      working-directory: ${{ inputs.working-directory }}
      run: docker images
      
