name: Docker push
description: Push docker image

inputs:
  image:
    required: true
    description: "Image to push"
  version-tag:
    required: true
    description: "Version to push"

runs:
  using: composite
  steps:
    - name: Build image
      shell: bash
      run: docker build . -t ${{ inputs.image }}:${{ inputs.version-tag }}

    - name: Tag latest
      shell: bash
      run: docker image tag ${{ inputs.image }}:${{ inputs.version-tag }} ${{ inputs.image }}:latest

    - name: Image
      shell: bash
      run: docker images
      
    - name: Push
      shell: bash
      run: docker push ${{ inputs.image }}:${{ inputs.version-tag }}
