name: Docker push
description: Push docker image 

inputs: 
  working-directory:
    required: true
    description: "Location of Dockerfile"
  image-tag:
    required: true
    description: "Tag to push the new image to"

runs: 
  using: composite
  steps:
    - name: Test
      shell: bash
      working-directory: ${{ inputs.working-directory }}
      run: echo "hello"
    - name: Help
      shell: bash
      working-directory: ${{ inputs.working-directory }}
      run: docker --help
      
    - name: Build
      shell: bash
      working-directory: ${{ inputs.working-directory }}
      run: docker build . -t ${{ inputs.image-tag }}
      
    - name: Build
      shell: bash
      working-directory: ${{ inputs.working-directory }}
      run: docker images
      
