name: .NET Test
description: Build .NET project

inputs: 
  working-directory:
    required: true
    description: "Location of .sln file"

runs: 
  using: composite
  steps:
    - name: Restore dependencies
      working-directory: ${{ inputs.working-directory }}
      shell: bash
      run: dotnet restore

    - name: Test
      working-directory: ${{ inputs.working-directory }}
      shell: bash
      run: dotnet test --verbosity normal