name: Docker

on:
  workflow_call:

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
        with:
          persist-credentials: false

      - name: Get version
        id: version
        uses: "./.github/actions/get-version"
        with:
          directory-build-props-file: "./Directory.Build.props"
          metadata-separator: "-"

      - name: Print version
        run: echo ${STEPS_VERSION_OUTPUTS_VERSION_TAG}
        env:
          STEPS_VERSION_OUTPUTS_VERSION_TAG: ${{steps.version.outputs.version-tag }}

      - name: Docker push
        uses: "./.github/actions/docker-push"
        with:
          working-directory: "./"
          image-tag: ghcr.io/vidarandrebo/bikeservice/${{steps.version.outputs.version-tag }}
          
