name: Docker

on:
  workflow_call:

jobs:
  build:
    permissions:
      contents: write
    name: Build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
        with:
          persist-credentials: true

      - name: Get version
        id: version
        uses: "./.github/actions/get-version"
        with:
          directory-build-props-file: "./Directory.Build.props"
          metadata-separator: "-"

      - name: Docker push
        uses: "./.github/actions/docker-push"
        with:
          image: ghcr.io/vidarandrebo/bikeservice
          version-tag: ${{steps.version.outputs.version-tag }}
          
      - name: Print version
        run: echo ${STEPS_VERSION_OUTPUTS_VERSION_TAG}
        env:
          STEPS_VERSION_OUTPUTS_VERSION_TAG: ${{steps.version.outputs.version-tag }}
