name: .NET

on:
  workflow_call:
    inputs:
      upload-artifact:
        default: false
        type: boolean

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0 # v7.0.0
        with:
          persist-credentials: false
      - name: Setup .NET
        uses: actions/setup-dotnet@9a946fdbd5fb07b82b2f5a4466058b876ab72bb2 # v5.3.0
        with:
          global-json-file: global.json
      - name: .NET Tool
        run: dotnet tool restore

      - name: .NET Test
        uses: "./.github/actions/dotnet-test"
        with:
          working-directory: "./"

      - name: .NET Build
        uses: "./.github/actions/dotnet-build"
        with:
          working-directory: "./"

      - name: Store artifact
        if: inputs.upload-artifact
        uses: actions/upload-artifact@043fb46d1a93c77aae656e7c1c64a875d1fc6a0a # v7.0.1
        with:
          name: "server"
          path: "./bin"
