name: Frontend/Vue
on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: setup
        working-directory: src/WebUI
        run: npm install
      - name: build
        working-directory: src/WebUI
        run: npm run build
