name: "On PR Changed"

on: 
  pull_request:
    branches:
      - main

jobs:
  dotnet:
    name: ".NET"
    uses: "./.github/workflows/dotnet.yml"
    with:
      upload-artifact: true

  vue:
    name: "Vue"
    uses: "./.github/workflows/vue.yml"
    with:
      upload-artifact: true

  publish:
    needs: [dotnet, vue]
    name: "Publish"
    uses: "./.github/workflows/publish.yml"
    secrets: inherit