name: Publish

on: workflow_call

jobs:
  build-publish:
    name: "Build and Publish"

    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
      with:
        persist-credentials: false
    
    - name: Setup SSH
      uses: "./.github/actions/ssh"
      with:
        known-hosts: ${{secrets.KNOWN_HOSTS}}
        ssh-key: ${{secrets.SSH_KEY}}
        host: ${{secrets.SSH_HOST}}
        user: ${{secrets.SSH_USERNAME}}

    - name: Vue artifact
      uses: actions/download-artifact@v4
      with:
        name: "client"
        path: "./static"

    - name: .NET artifact
      uses: actions/download-artifact@v4
      with:
        name: "server"
        path: "./bin"

    - name: Make binary executable
      run: chmod +x ./bin/BikeService.Server

    - name: Copy frontend dist to output dir
      run: cp -R ./static bin/wwwroot

    - name: Remove previous version
      run: ssh ${{ secrets.SSH_HOST }} rm -r bikeservice

    - name: Transfer
      run: |
        rsync -r bin/ ${{ secrets.SSH_HOST }}:bikeservice
      shell: bash

    - name: SHA
      run: |
        echo ${{ github.event.pull_request.head.sha }} > commit-hash.txt
        rsync commit-hash.txt ${{ secrets.SSH_HOST }}:bs-commit-hash.txt
      shell: bash
