name: Tag

on: 
  push:


jobs:
  tag-api:
    name: "Tag"
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v6
      with:
        persist-credentials: false

    - name: Grep
      run: grep '<Version>' Directory.Build.props | sed -E 's/.*<Version>([^<]+)<\/Version>.*/\1/'

    - name: version
      run: date +%Y%m%d%H%M%S