name: Tag

on:
  workflow_call:

permissions:
  contents: write

jobs:
  tag-api:
    name: "Tag"
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
        with:
          persist-credentials: true

      - name: Get version
        id: version
        uses: "./.github/actions/get-version"
        with:
          directory-build-props-file: "./Directory.Build.props"

      - name: Print version
        run: echo ${STEPS_VERSION_OUTPUTS_VERSION_TAG}
        env:
          STEPS_VERSION_OUTPUTS_VERSION_TAG: ${{steps.version.outputs.version-tag }}

      - name: Configure Git
        shell: bash
        run: |
          git config --global user.name 'github-actions[bot]'
          git config --global user.email 'github-actions[bot]@users.noreply.github.com'

      - name: Create and push tag
        shell: bash
        run: |
          git tag ${STEPS_VERSION_OUTPUTS_VERSION_TAG} -m "BikeService version ${STEPS_VERSION_OUTPUTS_VERSION_TAG}"
          git push origin ${STEPS_VERSION_OUTPUTS_VERSION_TAG}
        env:
          STEPS_VERSION_OUTPUTS_VERSION_TAG: ${{ steps.version.outputs.version-tag }}
