name: Vue

on:
  workflow_call:
    inputs:
      upload-artifact:
        default: false
        type: boolean

jobs:
  build:
    name: "Build"
    defaults:
      run:
        working-directory: "./client/"


    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@df4cb1c069e1874edd31b4311f1884172cec0e10 # v6.0.3
        with:
          persist-credentials: false

      - name: Install pnpm
        uses: pnpm/action-setup@0ebf47130e4866e96fce0953f49152a61190b271 # v6.0.9
        with:
          package_json_file: "./src/Client/package.json"

      - name: Vue Build
        uses: "./.github/actions/vue-build"
        with:
          working-directory: "./src/Client"

      - name: Store artifact
        if: inputs.upload-artifact
        uses: actions/upload-artifact@043fb46d1a93c77aae656e7c1c64a875d1fc6a0a # v7.0.1
        with:
          name: "client"
          path: "./src/Client/dist"


